version: "3"

volumes:
  bloom-pg-data:


services:

  postgres:
    container_name: bloom-pg
    image: postgres:12.2-alpine
    volumes:
      - bloom-pg-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_PASSWORD=password
      # database name with mydb
      - POSTGRES_DB=bloom



